### PR TITLE
Added missing context parameter to workflow_apply

### PR DESCRIPTION
**Pull request by makroxyz**

### CODE REVIEW

**Comment by zerodahero** [comment]
Can you add in tests for this?

**Comment by makroxyz** [comment]
Sorry... I don't have time right now... :-(

Anyway have a look here https://symfony.com/doc/current/workflow.html (half page)

In Symfony 5.2, the context is accessible in all events:
```php
// $context must be an array
$context = ['context_key' => 'context_value'];
$workflow->apply($subject, $transitionName, $context); // <--- HERE

// in an event listener
$context = $event->getContext(); // returns ['context']
```

**Comment by zerodahero** [comment]
Yep, it's definitely a needed addition, it just needs to have tests.

I'll try and find some time to add tests then.

**Comment by makroxyz** [comment]
hi please merge

**Comment by zerodahero** [comment]
> hi please merge

@makroxyz sorry I haven't been able to find time to add tests to this. I will not be merging it without tests.

**Comment by zerodahero** [comment]
Thanks! Added to [v3.3.2](https://github.com/zerodahero/laravel-workflow/releases/tag/v3.3.2)!

**Pull request closed without merging**
